name: "Schedule event"

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: |
            **/go.sum

      - name: Execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER_NAME: ${{ github.repository_owner }}
          GITLAB_USER_ID: ${{ secrets.GITLAB_USER_ID }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: go run src/cmd/main.go
